#!/usr/bin/env python3
"""
工程坐标 → KML 文件（Google Earth 可视化）

把 Excel 中的坐标点导出为 KML 文件，双击即可在 Google Earth 中查看。
支持自定义点位图标颜色、名称、描述。

使用示例：
  python excel_to_kml.py --input 测量点.xlsx --name "项目名称" --lat latitude --lng longitude
  python excel_to_kml.py --input points.csv --name "钻孔点位" --desc "深度"
"""

import argparse
from pathlib import Path
import pandas as pd


KML_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
<Document>
  <name>{doc_name}</name>
  <description>Generated by Excel-to-KML tool</description>
  {placemarks}
</Document>
</kml>"""

PLACEMARK_TEMPLATE = """  <Placemark>
    <name>{name}</name>
    <description><![CDATA[{description}]]></description>
    <styleUrl>#{style_id}</styleUrl>
    <Point>
      <coordinates>{lng},{lat},0</coordinates>
    </Point>
  </Placemark>"""

STYLE_TEMPLATE = """  <Style id="{style_id}">
    <IconStyle>
      <color>{color}</color>
      <scale>1.0</scale>
      <Icon>
        <href>http://maps.google.com/mapfiles/kml/paddle/{icon}.png</href>
      </Icon>
    </IconStyle>
    <LabelStyle>
      <color>{color}</color>
      <scale>1.0</scale>
    </LabelStyle>
  </Style>"""

# 预定义图标颜色（KML 格式: AABBGGRR）
COLORS = {
    "red": "ff0000ff", "green": "ff00ff00", "blue": "ffff0000",
    "yellow": "ff00ffff", "orange": "ff00a5ff", "purple": "ffff007f",
    "white": "ffffffff", "pink": "ffff6eb4",
}
ICONS = {
    "red": "red-blank", "green": "grn-blank", "blue": "blu-blank",
    "yellow": "ylw-blank", "default": "red-blank",
}


def excel_to_kml(input_file: str, doc_name: str, lat_col: str,
                 lng_col: str, name_col: str = None, desc_col: str = None,
                 color: str = "red", output: str = "output.kml"):
    """将 Excel/CSV 中的坐标点导出为 KML"""
    input_path = Path(input_file)
    if not input_path.exists():
        print(f"❌ 文件不存在: {input_file}")
        return

    df = pd.read_excel(input_path) if input_path.suffix in (".xlsx", ".xls") \
         else pd.read_csv(input_path)

    # 验证列
    for col, label in [(lat_col, "纬度"), (lng_col, "经度")]:
        if col not in df.columns:
            print(f"❌ 找不到{label}列: '{col}'。可用列: {list(df.columns)}")
            return

    # 构建样式
    kml_color = COLORS.get(color, COLORS["red"])
    icon = ICONS.get(color, ICONS["default"])
    style = STYLE_TEMPLATE.format(style_id="defaultStyle",
                                  color=kml_color, icon=icon)

    # 构建点位
    placemarks = []
    for i, row in df.iterrows():
        lat, lng = float(row[lat_col]), float(row[lng_col])

        # 名称
        if name_col and name_col in df.columns:
            name = str(row[name_col])
        else:
            name = f"Point_{i+1}"

        # 描述
        desc_parts = []
        if desc_col and desc_col in df.columns:
            desc_parts.append(f"<b>{desc_col}:</b> {row[desc_col]}<br/>")
        # 自动添加所有数值列
        for col in df.columns:
            if col not in (lat_col, lng_col, name_col):
                val = row[col]
                if pd.notna(val):
                    desc_parts.append(f"<b>{col}:</b> {val}<br/>")

        description = "".join(desc_parts) if desc_parts else f"点位 {i+1}"
        placemark = PLACEMARK_TEMPLATE.format(
            name=name, description=description,
            style_id="defaultStyle", lng=lng, lat=lat
        )
        placemarks.append(placemark)

    # 组装 KML
    kml_content = KML_TEMPLATE.format(
        doc_name=doc_name,
        placemarks=style + "\n" + "\n".join(placemarks)
    )

    with open(output, "w", encoding="utf-8") as f:
        f.write(kml_content)

    print(f"✅ KML 文件已生成: {output}")
    print(f"   共 {len(placemarks)} 个点位")
    print(f"   颜色: {color}  |  双击文件可在 Google Earth 中打开")
    print(f"\n💡 提示：如果没有 Google Earth，也可上传到")
    print(f"   https://earth.google.com 在线查看")


def main():
    parser = argparse.ArgumentParser(
        description="Excel 坐标 → Google Earth KML 文件"
    )
    parser.add_argument("--input", required=True,
                        help="输入文件（CSV/Excel，含经纬度坐标）")
    parser.add_argument("--name", default="工程点位",
                        help="KML 文档名称 / 项目名称")
    parser.add_argument("--lat", required=True,
                        help="纬度列名")
    parser.add_argument("--lng", required=True,
                        help="经度列名")
    parser.add_argument("--name-col", default=None,
                        help="点位名称列名（可选，默认用 Point_1, Point_2...）")
    parser.add_argument("--desc-col", default=None,
                        help="主描述列名（可选）")
    parser.add_argument("--color", default="red",
                        choices=list(COLORS.keys()),
                        help="点位图标颜色（默认: red）")
    parser.add_argument("--output", default="output.kml",
                        help="输出 KML 文件路径")
    args = parser.parse_args()

    excel_to_kml(args.input, args.name, args.lat, args.lng,
                 args.name_col, args.desc_col, args.color, args.output)


if __name__ == "__main__":
    main()
